### ISSUE TITLE
Elm 0.18

### ISSUE THREAD

**Issue by simonewebdesign** [fbonetti/elm-rails#11]
Hi there, I appreciate Elm 0.18 is just out today, but I was wondering if you have any plans of supporting it?

**Comment by maleksiuk** [comment]
If it helps, my fork (https://github.com/maleksiuk/elm-rails) works with Elm 0.18.  I have only used elm-rails briefly for giving an Elm demo though so hopefully I didn't miss anything -- you will notice that my change is very minor.

**Comment by lsimoneau** [comment]
I've just merged #12. I've been using this branch with Elm 0.18 and everything works fine, so I'm closing this issue. Feel free to re-open if something's not working for you on the latest version.
