### ISSUE TITLE
I cannot find module...

### ISSUE THREAD

**Issue by almays** [fbonetti/elm-rails#17]
Hi.

I wrote a small elm component for my rails app. And it uses
```
import Bootstrap.Grid exposing (..)
import Bootstrap.Wells exposing (..)
```
I did `elm package install JeremyBellows/elm-bootstrapify` and it is in `elm-package.json`

But from Rails I get exception:
```
I cannot find module 'Bootstrap.Grid'.

Module 'PriceCalculator' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```
Am I wrong? Or JeremyBellows? Or it is something here?

**Comment by almays** [comment]
Well. It has nothing to do with `Bootstrap.Grid`. Compile breaks on the first non-base import.

**Comment by lsimoneau** [comment]
@almays where is your `elm-package.json` file located? It should be in the root of your Rails project. If you're still having issues can you post a sample project reproducing the issue?

**Comment by almays** [comment]
It was the moment, when github was down, so nothing new could be downloaded and installed.
Definitely closed issue.

**Comment by lsimoneau** [comment]
Thanks for letting me know.
