### ISSUE TITLE
Dependency Tracking

### ISSUE THREAD

**Issue by rtfeldman** [fbonetti/elm-rails#2]
Here's the snippet we've been using for our Sprockets integration at NoRedInk—it includes dependency tracking, so it will recompile the assets if any dependent file changes.

Hope it helps!

https://gist.github.com/rtfeldman/db7b121100b6c6ff435b

**Comment by fbonetti** [comment]
Thanks for the gist! It looks like a couple people have opened PRs to integrate this code into the project.
