### ISSUE TITLE
I cannot release a new version

### ISSUE THREAD

**Issue by botandrose** [fbonetti/elm-rails#29]
@fbonetti @lsimoneau I would like to release elm-rails v0.2.2, but I don't have the permissions. Can one of you add me to the rubygems owner's list?

```
gem owner elm-rails --add micah@botandrose.com
```

**Comment by botandrose** [comment]
@fbonetti @lsimoneau Ping

**Comment by fbonetti** [comment]
@botandrose added

**Comment by botandrose** [comment]
Success! https://rubygems.org/gems/elm-rails/versions/0.2.2

Elm-Rails v0.2.2 is out! It includes non-broken nested dependency tracking, and also expands the supported Ruby and Rails versions. :tada: :tada: :tada:
